[package]
name = "rbrep"
version = "0.1.0"
edition = "2021"
author = "Lukas Krickl <lukas@krickl.dev>"

[dependencies]
anyhow = "1.0.68"
clap = { version = "4.0.32", features = ["derive"] }
thiserror = "1.0.38"
